awk '
BEGIN { skipping = 0 }
/\/\/ Carousel/ {
    skipping = 1
    print "                // Carousel"
    print "                Column("
    print "                    modifier = Modifier"
    print "                        .fillMaxHeight()"
    print "                        .weight(1f),"
    print "                    horizontalAlignment = Alignment.CenterHorizontally,"
    print "                    verticalArrangement = Arrangement.Center"
    print "                ) {"
    print "                    if (games.isEmpty()) {"
    print "                        Text(\"NO GAMES INSTALLED\", color = TextSecondary, fontFamily = Rajdhani, fontSize = 2.4.cqhSp(m))"
    print "                    } else {"
    print "                        Row("
    print "                            verticalAlignment = Alignment.CenterVertically,"
    print "                            horizontalArrangement = Arrangement.SpaceBetween,"
    print "                            modifier = Modifier.fillMaxWidth()"
    print "                        ) {"
    print "                            IconButton(onClick = { activeGameIndex = (activeGameIndex + games.size - 1) % games.size }) {"
    print "                                Icon("
    print "                                    Icons.AutoMirrored.Filled.ArrowBack, "
    print "                                    contentDescription = \"Previous\", "
    print "                                    tint = TextSecondary, "
    print "                                    modifier = Modifier.size(3.4.cqh(m))"
    print "                                )"
    print "                            }"
    print "                            "
    print "                            // Games list display"
    print "                            val prev = (activeGameIndex + games.size - 1) % games.size"
    print "                            val next = (activeGameIndex + 1) % games.size"
    print "                            "
    print "                            listOf(prev, activeGameIndex, next).forEachIndexed { pos, i ->"
    print "                                val isActive = pos == 1"
    print "                                val g = games[i]"
    print "                                val size = if (isActive) 26.0.cqh(m) else 18.0.cqh(m)"
    print "                                "
    print "                                Column("
    print "                                    horizontalAlignment = Alignment.CenterHorizontally,"
    print "                                    modifier = Modifier.clickable { activeGameIndex = i }"
    print "                                ) {"
    print "                                    Box("
    print "                                        modifier = Modifier"
    print "                                            .size(size)"
    print "                                            .let {"
    print "                                                if (isActive) {"
    print "                                                    it.glow(PrimaryRed, 12.dp, CircleShape)"
    print "                                                      .border(2.dp, PrimaryRed, CircleShape)"
    print "                                                      .padding(1.4.cqh(m))"
    print "                                                } else {"
    print "                                                    it.padding(0.9.cqh(m))"
    print "                                                }"
    print "                                            }"
    print "                                    ) {"
    print "                                        Image("
    print "                                            painter = painterResource(id = g.imageResId),"
    print "                                            contentDescription = g.name,"
    print "                                            modifier = Modifier"
    print "                                                .fillMaxSize()"
    print "                                                .clip(CircleShape),"
    print "                                            contentScale = ContentScale.Crop,"
    print "                                            alpha = if (isActive) 1f else 0.65f"
    print "                                        )"
    print "                                    }"
    print "                                    if (!isActive) {"
    print "                                        Spacer(modifier = Modifier.height(1.0.cqh(m)))"
    print "                                        Text("
    print "                                            text = g.name, "
    print "                                            color = TextSecondary, "
    print "                                            fontSize = 1.9.cqhSp(m), "
    print "                                            fontWeight = FontWeight.Medium,"
    print "                                            fontFamily = Rajdhani"
    print "                                        )"
    print "                                    }"
    print "                                }"
    print "                            }"
    print "                            "
    print "                            IconButton(onClick = { activeGameIndex = (activeGameIndex + 1) % games.size }) {"
    print "                                Icon("
    print "                                    Icons.AutoMirrored.Filled.ArrowForward, "
    print "                                    contentDescription = \"Next\", "
    print "                                    tint = TextSecondary, "
    print "                                    modifier = Modifier.size(3.4.cqh(m))"
    print "                                )"
    print "                            }"
    print "                        }"
    print "                        "
    print "                        Spacer(modifier = Modifier.height(2.4.cqh(m)))"
    print "                        "
    print "                        Text("
    print "                            text = games[activeGameIndex].name.uppercase(),"
    print "                            color = TextPrimary,"
    print "                            fontSize = 3.6.cqhSp(m),"
    print "                            fontWeight = FontWeight.Bold,"
    print "                            fontFamily = Rajdhani,"
    print "                            letterSpacing = 0.05.sp"
    print "                        )"
    print "                        "
    print "                        Spacer(modifier = Modifier.height(1.0.cqh(m)))"
    print "                        "
    print "                        Box("
    print "                            modifier = Modifier"
    print "                                .width(9.0.cqh(m))"
    print "                                .height(0.5.cqh(m))"
    print "                                .glow(PrimaryRed, 4.dp, CircleShape)"
    print "                                .background(PrimaryRed, CircleShape)"
    print "                        )"
    print "                    }"
    print "                }"
}
/\/\/ Footer Actions/ {
    skipping = 0
}
{
    if (skipping == 0) {
        print $0
    }
}
' app/src/main/java/com/example/ui/screens/DashboardScreen.kt > tmp2.kt
mv tmp2.kt app/src/main/java/com/example/ui/screens/DashboardScreen.kt
