name: Build Release Apk

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'
          cache-disabled: true
          validate-wrappers: false

      - name: Build Release APK
        run: gradle assembleRelease --no-daemon

      - name: Sign APK
        id: sign_app
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > release.keystore
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          
          /usr/local/lib/android/sdk/build-tools/34.0.0/zipalign -v -p 4 "$APK_PATH" app-release-aligned.apk
          /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner sign --ks release.keystore --ks-pass "env:STORE_PASSWORD" --key-pass "env:KEY_PASSWORD" --ks-key-alias "$KEY_ALIAS" --out app-release-signed.apk app-release-aligned.apk
          
          echo "signedReleaseFile=app-release-signed.apk" >> "$GITHUB_OUTPUT"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
